version: '3'
services:
  myapp:
    container_name: simple-express-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 80:8000

    volumes:
      - ./:/usr/src/app

